"""da hui znaet

Revision ID: b6c53260a371
Revises: c89976f8464e
Create Date: 2024-07-17 23:22:23.160383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c53260a371'
down_revision = 'c89976f8464e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
